<a href="https://colab.research.google.com/github/Aumatell/Python_deep_learning-Practical_introduction_with_keras_and_tensorflow/blob/main/3_Python_and_its_libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> 

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [ ]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [ ]:
from random import randint
randomint = randint(1,100)
print(randomint)

13


In [ ]:
import random
randomint = random.randint(1,100)
print(randomint)

11


3.1.3 Variables, operators and data types

Data types

In [1]:
x=10
print(x)
print(type(x))

10
<class 'int'>


In [1]:
x="hola"
print(x)
print(type(x))

hola
<class 'str'>


In [2]:
x=10.0
print(x)
print(type(x))

10.0
<class 'float'>


In [3]:
x=True
print(x)
print(type(x))

True
<class 'bool'>


Operators

In [4]:
print(2/5)

0.4


In [5]:
print(5//2)

2


In [6]:
print(5%2)

1


In [7]:
print(2**5)

32


In [9]:
IntegerVar = 10
IntegerVar += 10
print(IntegerVar)

20


In [10]:
StringVar = "Deep"
StringVar += " learning"
print(StringVar)

Deep learning


In [11]:
IntegerVar, StringVar = StringVar, IntegerVar
print(IntegerVar)
print(StringVar)

Deep learning
20


3.1.4 Types of data structures

In [15]:
# list
x = [5, "hello", 1.8]
print(x)

[5, 'hello', 1.8]


In [13]:
len(x)

3

In [16]:
x.append(100)
print(x)
print(len(x))

[5, 'hello', 1.8, 100]
4


In [17]:
x[1] = "deep"
print(x)

[5, 'deep', 1.8, 100]


In [18]:
y = [2.1, "learning"]
z= x + y
print(z)

[5, 'deep', 1.8, 100, 2.1, 'learning']


In [20]:
x = [5, "deep", 1.8]
print("First element -->   x[0]: ", x[0])
print("Second element -->  x[1]: ", x[1])
print("Last element -->    x[-1]: ", x[-1])
print("Seond from last position element -->    x[-2]: ", x[-2])

First element -->   x[0]:  5
Second element -->  x[1]:  deep
Last element -->    x[-1]:  1.8
Seond from last position element -->    x[-2]:  deep


In [21]:
print("All elements -->    x[:]: ", x[:])
print("From index 1 to end -->    x[1:]: ", x[1:])
print("Index 1 to index 2 -->    x[1:2]: ", x[1:2])
print(" All but last -->    x[:-1]: ", x[:-1])

All elements -->    x[:]:  [5, 'deep', 1.8]
From index 1 to end -->    x[1:]:  ['deep', 1.8]
Index 1 to index 2 -->    x[1:2]:  ['deep']
 All but last -->    x[:-1]:  [5, 'deep']


Tupples

In [22]:
x = (1, "deep", 3)
print(x)
print(x[1])

(1, 'deep', 3)
deep


In [23]:
x=x+(4,"learning")
print(x)
print(x[-1])

(1, 'deep', 3, 4, 'learning')
learning


Dictionary

In [42]:
persona ={
    "Name" : "Paty Tasso",
    "profesion" : "Being Cool"
}
print(persona)
print(persona["Name"])
print(persona["profesion"])

{'Name': 'Paty Tasso', 'profesion': 'Being Cool'}
Paty Tasso
Being Cool


In [28]:
persona["profesion"] = "Being cooler than cool"
print(persona)

{'Name': 'Paty Tasso', 'profesion': 'Being cooler than cool'}


In [29]:
persona["group"] = 42
print(persona)

{'Name': 'Paty Tasso', 'profesion': 'Being cooler than cool', 'group': 42}


In [30]:
print(len(persona))

3


3.1.5 Flux control sentences

If

In [31]:
x = 6.5
if x < 5:
  puntuacion = "low"
elif x <=7 :
  puntuacion = "medium"
else:
  puntuacion = "high"
print(puntuacion)

medium


In [32]:
x = True
if x:
  print("The condition is true")

The condition is true


In [33]:
a = 20 
if a >= 22:
  print("Paris")
elif a <= 21:
  print("Barcelona")


Barcelona


In [34]:
b = 1 
print("Paris" if b >= 92 else "Barcelona")

Barcelona


For loop

In [35]:
for a in range (1,4):
  print(a)

1
2
3


In [37]:
Universities = [ "UPC", "UDG", "UVIC","UAB", "UB"]
for university in Universities:
  print(university)

UPC
UDG
UVIC
UAB
UB


In [39]:
for university in Universities:
  if university == "UVIC":
    break
  print(university)

UPC
UDG


In [40]:
for university in Universities:
  if university == "UVIC":
    continue
  print(university)

UPC
UDG
UAB
UB


While loop

In [41]:
x = 3
while x > 0:
  x = x - 1
  print(x)

2
1
0


3.1.6 Functions

In [43]:
def my_university(university = "UPC"):
  y= "My university is " + university
  return(y)

print(my_university("UAB"))
print(my_university())
print(my_university(university="UPV"))

My university is UAB
My university is UPC
My university is UPV


In [44]:
def foo():
  a,b =4,5
  return(a,b)
foo()

(4, 5)

In [45]:
fibonacci = (lambda x:1 if x <=2 else fibonacci(x-1) + fibonacci(x-2))
fibonacci(10)

55

Classes

In [1]:
class Calculadora (object):
  """ Class of a Calculator"""
  def __init__(self):
    """Initialization of the calculator class"""
    self.valor = 0
  def suma (self, n):
    """ Dma un numero n al valor """
    self.valor += n
  def getValor(self):
    """Obtai the value """
    return self.valor

In [2]:
calc= Calculadora()
calc.suma(2)
print(calc.getValor())
calc.suma(2)
print(calc.getValor())

2
4


In [5]:
vec = [1,2,3]
it = iter(vec)
next(it)

1

In [6]:
next(it)

2

In [8]:
print(type(vec))
print(type(it))

<class 'list'>
<class 'list_iterator'>


3.1.8 Decorators

In [9]:
def lets_print_hello():
  print("Hello")

lets_print_hello()

Hello


In [10]:
def lets_print_hello():
  print("Hello")

def my_decorator(func):
  def wrapper():
    print("Warning: I'm gonna say it")
    func()
    print("Warning: I've just said that, huh!")
  return wrapper

lets_print_hello = my_decorator(lets_print_hello) # this can be done with @my_decorator before the function deinition as on the next code chunk

lets_print_hello()

Hello


In [12]:
@my_decorator
def lets_print_hello():
  print("HELLO")

lets_print_hello()

HELLO


3.2 NumPy

---

Easy and eficient numeric calculus.
Pandas, matplotlib and Scikit-Learn is constructed over numpy.


3.2.1 Tensor


---
Keras uses a multidimentional array from numpy as basic data structure called TENSOR. The tensor has 3 main attributes: Number of axis, Shape and Type of data.




1.   Number of axis (*rank*)


*   A tensor with only one value is called scalar ( 0-dimentional or 0D tensor)
*   An array of numbers will be called vector (1D tensor)
*   An array of vectors wil be called matrix (2D tensor)
*   An array of matrix will create what we could visualize as a cube of data ( 3D tensor)
The array of 3D tensors will create a 4D tensor and so on up to N dimentions.

2.   Shape

* The shape consists on a touple of integers containing the amount of dimentions on each axis of the tensor. On python this attribute s called *shape*. A vector will have a shape consistng on ne scalar and a 0D tensor will have its shape empty.

3. Data type

*This attribute indicates the tye of data containes in the tensor: unit8, float32, float64... In rare ocasions there are tensors of type char (never string). In Numpy library this attribute is called dtype) 


In [13]:
import numpy as np
x = np.array(8)
print("x : ",x)
print("x ndim: ",x.ndim)
print("x shape: ",x.shape)
print("x size: ",x.size)
print("x dtype: ",x.dtype)

x :  8
x ndim:  0
x shape:  ()
x size:  1
x dtype:  int64


In [15]:
import numpy as np
x = np.array([2.3,4.2,3.3,1.8])
print("x : ",x)
print("x ndim: ",x.ndim)
print("x shape: ",x.shape)
print("x size: ",x.size)
print("x dtype: ",x.dtype)

x :  [2.3 4.2 3.3 1.8]
x ndim:  1
x shape:  (4,)
x size:  4
x dtype:  float64


In [18]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("x :\n",x)
print("x ndim: ",x.ndim)
print("x shape: ",x.shape)
print("x size: ",x.size)
print("x dtype: ",x.dtype)

x :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
x ndim:  2
x shape:  (3, 3)
x size:  9
x dtype:  int64


In [19]:
import numpy as np
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("x :\n",x)
print("x ndim: ",x.ndim)
print("x shape: ",x.shape)
print("x size: ",x.size)
print("x dtype: ",x.dtype)

x :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape:  (2, 2, 2)
x size:  8
x dtype:  int64


In [22]:
print("np.zeros((3,3)) : \n ", np.zeros((3,3)))
print("np.ones((3,3)) : \n ", np.ones((3,3)))
print("np.eye((3)) (identity matrix) : \n ", np.eye((3)))
print("np.random.random((3,3)) : \n ", np.random.random((3,3)))


np.zeros((3,3)) : 
  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
np.ones((3,3)) : 
  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
np.eye((3)) (identity matrix) : 
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.random.random((3,3)) : 
  [[0.14181362 0.08897645 0.70406138]
 [0.07430771 0.2776339  0.09874808]
 [0.25197838 0.9870182  0.74666306]]


3.2.2 Tensor manipulation

In [23]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print("x column 1: ", x[:,1])
print("x row 0: ", x[0,:])
print("x rows 0,1 & cols 1,2: \n", x[0:2,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


In [24]:
a = np.array([[1,2,3],[4,5,6]], dtype= np.int32)
b = np.array([[7,8],[9,10],[11,12]], dtype= np.int32)
c=a.dot(b)
print(f"{a.shape} · {b.shape} = {c.shape}")
print(c)

(2, 3) · (3, 2) = (2, 2)
[[ 58  64]
 [139 154]]


In [26]:
x = np.array([[1,2,3,4,5,6]])
print(x)
print("x.shape :",x.shape)
y= np.reshape(x,(2,3))
print("y :\n",y)
print("y.shape :", y.shape)
z = np.reshape(x,(2,-1))
print("z :\n",z)
print("z.shape :", z.shape)

[[1 2 3 4 5 6]]
x.shape : (1, 6)
y :
 [[1 2 3]
 [4 5 6]]
y.shape : (2, 3)
z :
 [[1 2 3]
 [4 5 6]]
z.shape : (2, 3)


In [28]:
x = np.array([[1,2,3],[4,5,6]])
print("x:\n",x)
print("x.shape: ",x.shape)
y = np.expand_dims(x,1)
print("y:\n", y)
print("y.shape :",y)

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y:
 [[[1 2 3]]

 [[4 5 6]]]
y.shape : [[[1 2 3]]

 [[4 5 6]]]


In [29]:
x= np.array([[[1,2,3]],[[4,5,6]]])
print("x:\n",x)
print("x.shape: ",x.shape)
y = np.squeeze(x,1)
print("y:\n", y)
print("y.shape :",y)


x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y:
 [[1 2 3]
 [4 5 6]]
y.shape : [[1 2 3]
 [4 5 6]]


3.2.3 Maximum value of a tensor

In [30]:
x =np.array([1,2,3,4])
print(x)

print(np.argmax(x)) # position of max value
print(np.max(x))    # Max value

[1 2 3 4]
3
4


In [31]:
x= np.array([1,2,4,4])
print(x)

print(np.argmax(x)) # position of the first max value
print(np.max(x))    # Max value

[1 2 4 4]
2
4


In [32]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print(np.argmax(x)) # position of the first max value
print(np.max(x))    # Max value

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
11
12


In [33]:
print(np.argmax(x, axis = 0))
print(np.max(x, axis = 0))

print(np.argmax(x, axis = 1))
print(np.max(x, axis = 1))

[2 2 2 2]
[ 9 10 11 12]
[3 3 3]
[ 4  8 12]
